Refactor

diff --git a/mkvrg b/mkvrg
--- a/mkvrg
+++ b/mkvrg
@@ -22,13 +22,13 @@ LICENSE
 
 cat > /dev/null <<DESCRIPTION
     Bash script for analyzing audio tracks in matroska files with ffmpeg and
-    applying replaygain (EBU r128) track and sample peak information
+    applying replaygain (EBU r128) gain and peak information
     with mkvpropedit, this avoids remuxing the matroksa file.
     Pass list of files or a directory to scan files, if you pass a
     directory it will recursively search in it for files.
     It will only work on files with these extensions: "mkv, mka, mk3d".
     
-    Requires: ffmpeg ffprobe mkvpropedit
+    Requires: ffmpeg mkvpropedit
     
     examples:
     ./mkvrg                  ; Recursive search in current folder for matroska files.
@@ -67,9 +67,16 @@ REMUX=${REMUX:-true}
 # Set to a full path to use a different ffmpeg executable.
 FFMPEG=${FFMPEG:-"ffmpeg"}
 
+# Reference loudness to use.
+# EBU R128 default is -23.00
+# Rreplaygain 1.0 and 2.0 default is -18.00
+REFLOUDNESS=${REFLOUDNESS:-"-23.00"}
+
 #########################################################################################
 #########################################################################################
 #########################################################################################
+
+RG_ALGO="EBU R128"
 
 if [[ ! $PEAKTYPE =~ ^(sample|true)$ ]]; then
     echo -e "\e[31mERROR: PEAKTYPE must be either sample or true.\e[0m"
@@ -81,10 +88,10 @@ if ! which "$FFMPEG" &> /dev/null; then
     exit 1
 fi
 
-REQPROGS="ffprobe file find grep mkvpropedit tr"
+REQPROGS="awk file find grep mkvpropedit mktemp sed"
 for PROG in $REQPROGS; do
     if ! which "$PROG" &> /dev/null; then
-        echo -e "\e[31mERROR: This program is required: $PROG\e[0m"
+        echo -e "\e[31mERROR: This program could not be found: $PROG\e[0m"
         exit 1
     fi
 done
@@ -95,26 +102,25 @@ if [[ ! -f $TMPFILE ]] || [[ ! -w $TMPFILE ]]; then
     exit 1
 fi
 
-REFLOUDNESS="-23.0"
+if [[ ! $REFLOUDNESS =~ ^\-?[0-9]{1,2}\.[0-9]{2}$ ]]; then
+    echo -e "\e[31mERROR: Invalid REFLOUDNESS format.\e[0m"
+    exit 1
+fi
 REFLOUDNESSINT=${REFLOUDNESS//\.[0-9]*/}
 
 trap cleantmp SIGHUP SIGINT SIGQUIT SIGTERM
-
 function cleantmp() {
     [[ -f $muxinfile && -f $muxoutfile ]] && rm "$muxoutfile"
     rm -f "$TMPFILE"
-    if [[ -n $1 ]]; then
-        exit "$1"
-    fi
-    exit 1
+    [[ -n $1 ]] && exit "$1" || exit 1
 }
 
-function lufsToLu() {
-    awk "BEGIN{print ($REFLOUDNESS - $1)}"
+function lufsTodB() {
+    printf "%0.2f" "$(awk "BEGIN{print ($REFLOUDNESS - $1)}")"
 }
 
 function dBtoAmplitude() {
-    awk "BEGIN{print 10^($1/20)}"
+    printf "%06f" "$(awk "BEGIN{print 10^($1/20)}")"
 }
 
 if [[ $REMUX == true ]]; then
@@ -124,7 +130,7 @@ if [[ $REMUX == true ]]; then
         muxoutfile=${muxoutfile//\.[mM][pP]4/.mkv}
         if [[ $muxinfile == "$muxoutfile" ]]; then
             # So cleanTmp() doesn't delete $muxinfile
-            muxoutfile=/tmp/fakeFile
+            muxoutfile=/tmp/rgfile
             continue
         fi
         echo "INFO: Remuxing '$muxinfile' to '$muxoutfile'."
@@ -139,36 +145,33 @@ i=0
 while read -r file; do
     file="$(realpath "$file")"
     if [[ ! $(file "$file") =~ "Matroska" ]]; then
-        echo -e "\e[92mNOTICE: '$file' is not a mkv file.\e[0m"
+        echo -e "\e[92mNOTICE: '$file' is not a matroska file.\e[0m"
         continue
     fi
     
-    FFPROBEOUT=$(ffprobe -hide_banner -i "$file" 2>&1)
-    if [[ ! $FORCE == true ]] && [[ $VERIFY == true ]] && [[ "$FFPROBEOUT" =~ BS\.1770 ]]; then
+    FFMPEG_OUT=$("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1)
+    if [[ ! $FORCE == true ]] && [[ $VERIFY == true ]] && [[ "$FFMPEG_OUT" =~ ${RG_ALGO} ]]; then
         echo -e "\e[92mNOTICE: Skipping, replaygain tags already exist on file '$file'\e[0m"
         continue
     fi
     
-    tracks=$(echo "$FFPROBEOUT" | grep -Poi "Stream\s*#\d+:\d+.+?Audio" | grep -Po "\d+:\d+" | cut -d : -f 2)
+    tracks=$(echo "$FFMPEG_OUT" | grep -Poi "Stream\s*#\d+:\d+.+?Audio" | grep -Po "\d+:\d+" | cut -d : -f 2)
     if [[ $tracks == "" ]]; then
         echo -e "\e[93mWARNING: Could not get track list for '$file'.\e[0m"
         continue
     fi
     
-    fileprocessed=0
+    tracksProcessed=0
     for track in $tracks; do
-        ffmpegTrack=$((track-1))
         echo "INFO: Running ffmpeg (using $PEAKTYPE peak calculation), this can take a while. (track $track on file '$file')"
-        FFMPEG_CMD="$FFMPEG -loglevel info -nostats -nostdin -hide_banner -i \"$file\" -map 0:a -filter_complex \"[0:a:$ffmpegTrack]ebur128=peak=$PEAKTYPE:framelog=quiet:target=$REFLOUDNESSINT\" -f null -"
+        FFMPEG_CMD="$FFMPEG -loglevel info -nostats -nostdin -hide_banner -i \"$file\" -map 0:a -filter_complex \"[0:a:$((track-1))]ebur128=peak=$PEAKTYPE:framelog=quiet:target=$REFLOUDNESSINT\" -f null -"
         echo "$FFMPEG_CMD"
         FFMPEG_OUT=$(eval "$FFMPEG_CMD" 2>&1 | tr "\n" " " | sed "s/^.*\(Parsed_ebur128.*$\)/\1/" | sed "s/ \+/ /g")
         echo "$FFMPEG_OUT"
-        TRACKGAIN=$(echo "$FFMPEG_OUT" | grep -Po " I: -?[\d.]+ LUFS" | cut -d\  -f3)
-        TRACKGAIN=$(lufsToLu "$TRACKGAIN")
-        TRACKPEAK=$(echo "$FFMPEG_OUT" | grep -Po " Peak: -?[\d.]+ dBFS" | cut -d\  -f3)
-        TRACKPEAK=$(dBtoAmplitude "$TRACKPEAK")
+        TRACKGAIN=$(lufsTodB "$(echo "$FFMPEG_OUT" | grep -Po " I: -?[\d.]+ LUFS" | cut -d\  -f3)")
+        TRACKPEAK=$(dBtoAmplitude "$(echo "$FFMPEG_OUT" | grep -Po " Peak: -?[\d.]+ dBFS" | cut -d\  -f3)")
         if [[ $TRACKGAIN == "" ]] || [[ $TRACKPEAK == "" ]]; then
-            echo -e "\e[92mNOTICE: Problem finding replaygain info from ffmpeg for track $track on file '$file'.\e[0m"
+            echo -e "\e[92mNOTICE: Problem finding $RG_ALGO info from ffmpeg for track $track on file '$file'.\e[0m"
             continue
         fi
         
@@ -181,7 +184,7 @@ while read -r file; do
     </Targets>
     <Simple>
       <Name>REPLAYGAIN_ALGORITHM</Name>
-      <String>BS.1770</String>
+      <String>$RG_ALGO</String>
     </Simple>
     <Simple>
       <Name>REPLAYGAIN_REFERENCE_LOUDNESS</Name>
@@ -198,24 +201,17 @@ while read -r file; do
   </Tag>
 </Tags>" > "$TMPFILE"
         
-        echo "INFO: Applying gain ($TRACKGAIN LU), peak ($TRACKPEAK amplitude) for track $track on file '$file'."
-
+        echo "INFO: Applying gain ($TRACKGAIN dB), peak ($TRACKPEAK amplitude) for track $track on file '$file'."
         mkvpropedit --tags track:"$((++track))":"$TMPFILE" "$file"
-        
-        if [[ $VERIFY == true ]] && [[ ! $(ffprobe -hide_banner -i "$file" 2>&1) =~ BS\.1770 ]]; then
+        if [[ $VERIFY == true ]] && [[ ! $("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1) =~ ${RG_ALGO} ]]; then
             echo -e "\e[93mWARNING: Replaygain has not been applied for track $track on file '$file'.\e[0m"
             continue
         fi
-        ((fileprocessed++))
+        ((tracksProcessed++))
     done
-    if [[ $fileprocessed -gt 0 ]]; then
+    if [[ $tracksProcessed -gt 0 ]]; then
         ((i++))
     fi
 done < <(find "$@" -type f -size "$MINSIZE" \( -iname "*.mk[av]" -o -iname "*.mk3d" \))
 
-# If you process a single file, you can use the exit status to know if the file was processed or not,
-# which is useful if you're using this script inside another script.
-if [[ $i == 0 ]]; then
-    cleantmp 1
-fi
-cleantmp 0
+[[ $i -gt 0 ]] && cleantmp 0
