Refactor

diff --git a/mkvrg b/mkvrg
--- a/mkvrg
+++ b/mkvrg
@@ -77,10 +77,8 @@ REFLOUDNESS=${REFLOUDNESS:-"-23.00"}
 PEAKTYPE=${PEAKTYPE:-"true"}
 
 #########################################################################################
+################################### Settings End ########################################
 #########################################################################################
-#########################################################################################
-
-RG_ALGO="EBU R128"
 
 if [[ ! $PEAKTYPE =~ ^(sample|true)$ ]]; then
     echo -e "\e[31mERROR: PEAKTYPE must be either sample or true.\e[0m"
@@ -92,17 +90,18 @@ if ! which "$FFMPEG" &> /dev/null; then
     exit 1
 fi
 
-REQPROGS="awk file find grep mkvpropedit mktemp sed"
-for PROG in $REQPROGS; do
-    if ! which "$PROG" &> /dev/null; then
-        echo -e "\e[31mERROR: This program could not be found: $PROG\e[0m"
+reqProgs="awk file find grep mkvpropedit mktemp sed"
+for reqProg in $reqProgs; do
+    if ! which "$reqProg" &> /dev/null; then
+        echo -e "\e[31mERROR: This program could not be found: $reqProg\e[0m"
         exit 1
     fi
 done
+unset reqProg reqProgs
 
-TMPFILE="$(mktemp)"
-if [[ ! -f $TMPFILE ]] || [[ ! -w $TMPFILE ]]; then
-    echo -e "\e[31mERROR: Could not create temp file $TMPFILE. Check permissions.\e[0m"
+tmpFile="$(mktemp)"
+if [[ ! -f $tmpFile ]] || [[ ! -w $tmpFile ]]; then
+    echo -e "\e[31mERROR: Could not create temp file $tmpFile. Check permissions.\e[0m"
     exit 1
 fi
 
@@ -110,12 +109,13 @@ if [[ ! $REFLOUDNESS =~ ^\-?[0-9]{1,2}\.[0-9]{2}$ ]]; then
     echo -e "\e[31mERROR: Invalid REFLOUDNESS format.\e[0m"
     exit 1
 fi
-REFLOUDNESSINT=${REFLOUDNESS//\.[0-9]*/}
+refLoudnessInt=${REFLOUDNESS//\.[0-9]*/}
+rgAlgo="EBU R128"
 
 trap cleantmp SIGHUP SIGINT SIGQUIT SIGTERM
 function cleantmp() {
-    [[ -f $muxinfile && -f $muxoutfile ]] && rm "$muxoutfile"
-    rm -f "$TMPFILE"
+    [[ -f $muxInFile && -f $muxOutFile ]] && rm -f "$muxOutFile"
+    rm -f "$tmpFile"
     [[ -n $1 ]] && exit "$1" || exit 1
 }
 
@@ -129,20 +129,24 @@ function dBtoAmplitude() {
 
 if [[ $REMUX == true ]]; then
     while read -r file; do
-        muxinfile="$(realpath "$file")"
-        muxoutfile=${muxinfile//\.[mM][oO][vV]/.mkv}
-        muxoutfile=${muxoutfile//\.[mM][pP]4/.mkv}
-        if [[ $muxinfile == "$muxoutfile" ]]; then
-            # So cleanTmp() doesn't delete $muxinfile
-            muxoutfile=/tmp/rgfile
+        muxInFile="$(realpath "$file")"
+        muxOutFile=${muxInFile//\.[mM][oO][vV]/.mkv}
+        muxOutFile=${muxOutFile//\.[mM][pP]4/.mkv}
+        if [[ $muxInFile == "$muxOutFile" ]]; then
+            unset muxInFile muxOutFile
             continue
         fi
-        echo "INFO: Remuxing '$muxinfile' to '$muxoutfile'."
-        "$FFMPEG" -y -loglevel error -stats -nostdin -hide_banner -i "$muxinfile" -c copy "$muxoutfile" && rm -f "$muxinfile"
+        echo "INFO: Remuxing '$muxInFile' to '$muxOutFile'."
+        if "$FFMPEG" -y -loglevel error -stats -nostdin -hide_banner -i "$muxInFile" -c copy "$muxOutFile"; then
+            rm -f "$muxInFile"
+        else
+            rm -f "$muxOutFile"
+        fi
+        unset muxInFile muxOutFile
     done < <(find "$@" -type f -size "$MINSIZE" \( -iname "*.mp4" -o -iname "*.mov" \))
 fi
 
-i=0
+filesProcessed=0
 while read -r file; do
     file="$(realpath "$file")"
     if [[ ! $(file "$file") =~ "Matroska" ]]; then
@@ -150,13 +154,13 @@ while read -r file; do
         continue
     fi
 
-    FFMPEG_OUT=$("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1)
-    if [[ ! $FORCE == true ]] && [[ $VERIFY == true ]] && [[ "$FFMPEG_OUT" =~ ${RG_ALGO} ]]; then
+    ffmpegOut=$("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1)
+    if [[ ! $FORCE == true ]] && [[ $VERIFY == true ]] && [[ "$ffmpegOut" =~ ${rgAlgo} ]]; then
         echo -e "\e[92mNOTICE: Skipping, replaygain tags already exist on file '$file'\e[0m"
         continue
     fi
 
-    tracks=$(echo "$FFMPEG_OUT" | grep -Poi "Stream\s*#\d+:\d+.+?Audio" | grep -Po "\d+:\d+" | cut -d : -f 2)
+    tracks=$(echo "$ffmpegOut" | grep -Poi "Stream\s*#\d+:\d+.+?Audio" | grep -Po "\d+:\d+" | cut -d : -f 2)
     if [[ $tracks == "" ]]; then
         echo -e "\e[93mWARNING: Could not get track list for '$file'.\e[0m"
         continue
@@ -165,54 +169,50 @@ while read -r file; do
     tracksProcessed=0
     for track in $tracks; do
         echo "INFO: Running ffmpeg (using $PEAKTYPE peak calculation), this can take a while. (track $track on file '$file')"
-        FFMPEG_CMD="$FFMPEG -loglevel info -nostats -nostdin -hide_banner -i \"$file\" -map 0:a -filter_complex \"[0:a:$((track-1))]ebur128=peak=$PEAKTYPE:framelog=quiet:target=$REFLOUDNESSINT\" -f null -"
-        echo "$FFMPEG_CMD"
-        FFMPEG_OUT=$(eval "$FFMPEG_CMD" 2>&1 | tr "\n" " " | sed "s/^.*\(Parsed_ebur128.*$\)/\1/" | sed "s/ \+/ /g")
-        echo "$FFMPEG_OUT"
-        TRACKGAIN=$(lufsTodB "$(echo "$FFMPEG_OUT" | grep -Po " I: -?[\d.]+ LUFS" | cut -d\  -f3)")
-        TRACKPEAK=$(dBtoAmplitude "$(echo "$FFMPEG_OUT" | grep -Po " Peak: -?[\d.]+ dBFS" | cut -d\  -f3)")
-        if [[ $TRACKGAIN == "" ]] || [[ $TRACKPEAK == "" ]]; then
-            echo -e "\e[92mNOTICE: Problem finding $RG_ALGO info from ffmpeg for track $track on file '$file'.\e[0m"
+        ffmpegCmd="$FFMPEG -loglevel info -nostats -nostdin -hide_banner -i \"$file\" -map 0:a -filter_complex \"[0:a:$((track-1))]ebur128=peak=$PEAKTYPE:framelog=quiet:target=$refLoudnessInt\" -f null -"
+        echo "$ffmpegCmd"
+        ffmpegOut=$(eval "$ffmpegCmd" 2>&1 | tr "\n" " " | sed "s/^.*\(Parsed_ebur128.*$\)/\1/" | sed "s/ \+/ /g")
+        echo "$ffmpegOut"
+        trackGain=$(lufsTodB "$(echo "$ffmpegOut" | grep -Po " I: -?[\d.]+ LUFS" | cut -d\  -f3)")
+        trackPeak=$(dBtoAmplitude "$(echo "$ffmpegOut" | grep -Po " Peak: -?[\d.]+ dBFS" | cut -d\  -f3)")
+        if [[ $trackGain == "" ]] || [[ $trackPeak == "" ]]; then
+            echo -e "\e[92mNOTICE: Problem finding $rgAlgo info from ffmpeg for track $track on file '$file'.\e[0m"
             continue
         fi
 
         echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>
+            <!DOCTYPE Tags SYSTEM \"matroskatags.dtd\">
+            <Tags>
+                <Tag>
+                    <Targets>
+                    </Targets>
+                    <Simple>
+                        <Name>REPLAYGAIN_ALGORITHM</Name>
+                        <String>$rgAlgo</String>
+                    </Simple>
+                    <Simple>
+                        <Name>REPLAYGAIN_REFERENCE_LOUDNESS</Name>
+                        <String>$REFLOUDNESS LUFS</String>
+                    </Simple>
+                    <Simple>
+                        <Name>REPLAYGAIN_TRACK_GAIN</Name>
+                        <String>$trackGain dB</String>
+                    </Simple>
+                    <Simple>
+                        <Name>REPLAYGAIN_TRACK_PEAK</Name>
+                        <String>$trackPeak</String>
+                    </Simple>
+                </Tag>
+            </Tags>" | sed "s/^            //g" > "$tmpFile"
 
-<!DOCTYPE Tags SYSTEM \"matroskatags.dtd\">
-<Tags>
-  <Tag>
-    <Targets>
-    </Targets>
-    <Simple>
-      <Name>REPLAYGAIN_ALGORITHM</Name>
-      <String>$RG_ALGO</String>
-    </Simple>
-    <Simple>
-      <Name>REPLAYGAIN_REFERENCE_LOUDNESS</Name>
-      <String>$REFLOUDNESS LUFS</String>
-    </Simple>
-    <Simple>
-      <Name>REPLAYGAIN_TRACK_GAIN</Name>
-      <String>$TRACKGAIN dB</String>
-    </Simple>
-    <Simple>
-      <Name>REPLAYGAIN_TRACK_PEAK</Name>
-      <String>$TRACKPEAK</String>
-    </Simple>
-  </Tag>
-</Tags>" > "$TMPFILE"
-
-        echo "INFO: Applying gain ($TRACKGAIN dB), peak ($TRACKPEAK amplitude) for track $track on file '$file'."
-        mkvpropedit --tags track:"$((++track))":"$TMPFILE" "$file"
-        if [[ $VERIFY == true ]] && [[ ! $("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1) =~ ${RG_ALGO} ]]; then
+        echo "INFO: Applying gain ($trackGain dB), peak ($trackPeak amplitude) for track $track on file '$file'."
+        mkvpropedit --tags track:"$((++track))":"$tmpFile" "$file"
+        if [[ $VERIFY == true ]] && [[ ! $("$FFMPEG" -nostdin -hide_banner -i "$file" 2>&1) =~ ${rgAlgo} ]]; then
             echo -e "\e[93mWARNING: Replaygain has not been applied for track $track on file '$file'.\e[0m"
             continue
         fi
         ((tracksProcessed++))
     done
-    if [[ $tracksProcessed -gt 0 ]]; then
-        ((i++))
-    fi
+    [[ $tracksProcessed -gt 0 ]] && ((filesProcessed++))
 done < <(find "$@" -type f -size "$MINSIZE" \( -iname "*.mk[av]" -o -iname "*.mk3d" \))
-
-[[ $i -gt 0 ]] && cleantmp 0
+[[ $filesProcessed -gt 0 ]] && cleantmp 0
